### PR TITLE
TH1D -> TH1, TH2D -> TH2, includes clean-up

### PR DESCRIPTION
**Pull request by greenwald**
This address issue #61

### CODE REVIEW

**Comment by oschulz** [comment]
Non-trivial merge conflicts with current master.

**Comment by greenwald** [comment]
This was mergeable when submitted. Can we aim to attack pull requests in the order submitted?

**Comment by oschulz** [comment]
> This was mergeable when submitted. Can we aim to attack pull requests in the order submitted?

This is being help up by #72. I want that one merged first (with all tests passing), so that I can properly test pull requests like this one. Otherwise, we might play endless catch up on #72 if new things break (as happened with one of the last merges before).

**Comment by oschulz** [comment]
> This was mergeable when submitted.

The clean merge probably broke when I merged "dev" with "master". Some old pull requests been merged into "dev", which ended up being some kind of secondary master branch. To get rid of it, I had to merge it first, sorry.

**Comment by fredRos** [comment]
We fixed the conflicts, merged in 7be1269

**Pull request closed without merging**
