### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by greenwald**
The merge undoes the parallel_TEST changes.

The rest refactors the models/base classes so that they don't have code repeats and can work with parallelization.

### CODE REVIEW

**Comment by oschulz** [comment]
Should the "efficiencyFitterExample.C" run now? I get

```
$ root -l efficiencyFitterExample.C
Summary : Opening logfile log.txt
Summary : Marginalize using Metropolis
Summary : Pre-run Metropolis MCMC for model "fitter_model_f1" ...
Summary :  --> Perform MCMC pre-run with 2 chains, each with maximum 10000 iterations

 *** Break *** segmentation violation

 *** Break *** segmentation violation
```

Or is this a different issue?

**Comment by greenwald** [comment]
It should not run if you have parallelization enabled. But it should run with it disabled. This pull is for code that is fully ready for parallelization; however, not if you run it in a ROOT macro. The error I get is about `GOMP_parallel` being undefined, because ROOT doesn't know about omp.

What was your configuration when you got this error?

**Comment by oschulz** [comment]
I did indeed configure with `--enable-roostats --with-cuba --enable-parallelization`. 
Interestingly, on another machine it seems to run (well, segfaults are like that ...).

**Comment by greenwald** [comment]
Can you check on the machine on which it ran if ROOT is somehow configured to know about omp? Which version of ROOT was it?

**Comment by oschulz** [comment]
It's root-6.04.02, and yes, the parallel examples run on all cores.

**Comment by greenwald** [comment]
This should still be ready for pulling. Are you guys waiting for something on this?

**Comment by fredRos** [comment]
I agree with @greenwald , but I thought @oschulz might have something against it. If not, I'm for accepting the pull request. I didn't check the commits individually but at least `histogramFitter` and `efficiencyFitter` work with multiple threads

**Comment by oschulz** [comment]
Nothing against it, I just didn't know if the segfaults should be fixed first. But I guess that's a different issue?

**Comment by fredRos** [comment]
I checked and didn't get a segfault anymore with the update branch. But of course I will let @oschulz test himself :smile:

**Comment by greenwald** [comment]
If there are segfaults, they should be unrelated to the material in the pull.

**Pull request merged**
