### PR TITLE
[install, tools] Reduce minimal ax_openmp autoconf version to 2.59

### LINKED ISSUE #286: lower autoconf requirement
v2.69 from 2012 is not available everywhere and only needed for openmp checks.

### PR DESCRIPTION
**Pull request by fredRos**
Fixes #286 and #285 

@greenwald  please test that this works on your system with an old version of autoconf

### CODE REVIEW

**Comment by greenwald** [comment]
I run into an error when doing the check:

> Making check in advancedGraphFitter
> make[3]: Entering directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples/advanced/advancedGraphFitter'
> make  check-TESTS
> make[4]: Entering directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples/advanced/advancedGraphFitter'
> /bin/sh: line 9: ./graphFitterAdvancedExample.C: Permission denied
> FAIL: graphFitterAdvancedExample.C
> ==================
> 1 of 1 test failed
> ==================
> make[4]: *** [check-TESTS] Error 1
> make[4]: Leaving directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples/advanced/advancedGraphFitter'
> make[3]: *** [check-am] Error 2
> make[3]: Leaving directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples/advanced/advancedGraphFitter'
> make[2]: *** [check-recursive] Error 1
> make[2]: Leaving directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples/advanced'
> make[1]: *** [check-recursive] Error 1
> make[1]: Leaving directory `/nfs/mnemosyne/user/dgreenw/private/work/bat/bat/examples'
> make: *** [check-recursive] Error 1

I also ran into an error in `BCModel_TEST.cxx`, which I've fixed. It is in my fork: greenwald/bat@3b43a5f620ce2c43e99ca021605bd48e49ee205b

**Comment by fredRos** [comment]
Can you run `make check` for master? I guess that fails, too. Seems to be an issue with your old environment. What are the versions you use for root, autoconf, g++? I suppose the missing `<stdexcept>` is due to changes long ago in the gcc header include order. If it fixes your problem, I'm happy to cherry-pick it.

**Comment by fredRos** [comment]
I'm confident it's automake and the test driver that's too old. in `install.md` I say we need 1.15 for the tests

**Comment by greenwald** [comment]
Yeah, I tried testing with version 1.11.1.

**Comment by fredRos** [comment]
Yes, that's enough. The tests pass on travis, so please approve, rebase and merge

**Pull request merged**
