### PR TITLE
[configure.ac] Add m4/ directory for libtool macros

### PR DESCRIPTION
**Pull request by fredRos**
Fixes error if autoconf and libtool are not installed in the default
location

configure.ac:8: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:8: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

### CODE REVIEW

**Comment by fredRos** [comment]
A small hold up. I created the original PR on Ubuntu 16.04. On a Debian Jessie, this still gives warnings. According to https://autotools.io/autoconf/macros.html, the macro `AC_CONFIG_MACRO_DIRS` was added in automake 1.13. On Jessie, I have

```
$ automake --version
automake (GNU automake) 1.14.1
$ ./autogen.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: You should add the contents of the following files to `aclocal.m4':
libtoolize:   `/usr/share/aclocal/libtool.m4'
libtoolize:   `/usr/share/aclocal/ltoptions.m4'
libtoolize:   `/usr/share/aclocal/ltversion.m4'
libtoolize:   `/usr/share/aclocal/ltsugar.m4'
libtoolize:   `/usr/share/aclocal/lt~obsolete.m4'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
```

If I then change in `configure.ac` from `AC_CONFIG_MACRO_DIRS` to `AC_CONFIG_MACRO_DIR` and rerun `autogen.sh`, `libtoolize` doesn't complain anymore. I checked and it also works on Ubuntu 16.04. It seems this is more backwards-compatible. The `*DIRS` option is only needed if we had multiple directories but we don't.

Now this is ready for merging, please run the tests.

**Comment by oschulz** [comment]
Will this work on older systems (e.g. SLC6)?

**Comment by fredRos** [comment]
> Tests passed on Ubuntu 14.04 and OS-X. 

Great

> But will this work on older systems (e.g. SLC6)?

No idea, do you mean scientific linux? I will try to check this next week on my colleague's machine. I don't have a container or anything available for that distro

**Comment by oschulz** [comment]
Yes, I mean Scientific Linux 6 (resp. CERN Scientific Linux 6). We won't get rid of it during LHC Run-II ...

**Comment by fredRos** [comment]
`autogen.sh` works fine on SL7. I couldn't get a hold of SL6. Please merge!

**Comment by oschulz** [comment]
> I couldn't get a hold of SL6. Please merge!

Sorry, I'd like to test this at our MPCDF cluster (running SLC6) first.

**Pull request merged**
