### PR TITLE
Added errorband related function to BCFitter

### PR DESCRIPTION
**Pull request by tquante**
Added the possibility to extend the errorband in Y and X range to cover cases in which the needed x or y range is higher than	 the default errorband range. One Example could be a calibration which has to be evaluated beyond the highest x point.

Added a function which returns a copy of the internal errorband histogram. In this case one could store it for later usage.

### CODE REVIEW

**Comment by fredRos** [comment]
I'm ok with the functionality. Some formal concerns: it doesn't quite conform to the bat code style. I think we can update this more easily than @tquante using our `make format` target, so let us do take care of that. 

Regarding `GetErrorBandXYCopy`: it would be more parsimonious to just have a getter
```c++
TH2& BCFitter::GetErrorBand() const
```
perhaps returning a `const&` and the user could copy it himself. Else for consistency, we would have to add many such `Get...Copy` methods. I"m not a big root expert, so I can't judge if `hist->SetDirectory(0);` is something every user would want, or if it should be under their control

**Comment by tquante** [comment]
I would also be happy with a simple getter. I introduced the Copy function because the getter method was removed from bat0.9.4 to bat 1.0. I thought this has something to do with preventing race conditions due to multi-threaded MCMC. If there is no such problem the getter should be good enough. 

Regarding the SetDirectory(0) this assures that the given histogram is not owned by the currently active TFile which can cause segfaults if this TFile is handled by bat and is closed before the usage of the copied histogram which can be very frustrating to debug. It is still possible to write the histogram to a TFile  which is owned by the user.

 I do know if it is the case, but if the internal bat histograms do not call this function they will end up in a TFile owned by the user if the file is opened before creating any of these. This could be a potential bug in case of multi-threading if the TFile is closed during a running MCMC, because it is cleaning up all histograms.

**Comment by oschulz** [comment]
Thomas, a getter that returns a const reference sounds good. Could you implement that?

Also, could you try doing a `make format`, and then commit the resulting code-style changes? You just need [astyle](http://astyle.sourceforge.net/).

**Comment by tquante** [comment]
I have changed the function to const TH1& GetErrorBandXY() and also used make format. Please check if the result is what was intended because there were several changes in formatting style which was never changed by me. Probably this was caused by using astyle directly on BCFitter at first, before using make format

**Comment by oschulz** [comment]
Tests passed.  @fredRos , are you happy with the API changes?

**Comment by fredRos** [comment]
I had a looked and made some minor changes to the doc strings, the update is in cb420aa

One thing came to my mind: should we check the sign of `extension` in `SetErrorBandExtensionLowEdgeX(double extension)`? It looks like it should be nonnegative...

**Comment by tquante** [comment]
> should we check the sign of extension in SetErrorBandExtensionLowEdgeX(double extension) and friends? It looks like it is intended to be nonnegative so should we allow negative values? This would reduce the range...

Yes this will reduce the range. I think there are pros and cons. On the one hand you could reduce the overhead in case that you only need the errorband in a smaller range. On the other hand this can be confusing if one is thinking that `SetErrorbandExtensionLowEdgeX(-10)` would be equal to 
low_edge - 10

**Comment by oschulz** [comment]
@fredRos ?

**Comment by fredRos** [comment]
Let's keep it simple and just describe in the doc string that a positive extension always grows the interval, and negative values shrink it. This gives users flexibility and we don't need to implement error checks, so the code is clean. @tquante could you please verify that negative arguments do not lead to a crash or anything? Then I'm happy to accept the request, and I thank you for your patience with us

**Comment by tquante** [comment]
I have tested it with the graph fitter example and tried to remove the errorband completely by subtracting 50 from the low edge and 50 from the up edge. This results in a minimal errorband caused by the dx and dy during the histogram creation.

I also tried to overshoot the histogram edges by subtracting more than the histogram width, which results in an empty errorband, but i never get any problems that cause a segfault or something like that.
I think this patch can be merged with the comments mentioned by fredRos

**Comment by fredRos** [comment]
great, thanks a lot! I guess I can't push a button to approve it because @oschulz did already. So please follow your testing procedures and merge, @oschulz !

**Pull request merged**
