### PR TITLE
Fleshed out basics section.

### PR DESCRIPTION
**Pull request by greenwald**

### CODE REVIEW

**Comment by fredRos** [comment]
I pushed more improvements to my repo on top of your changes in
fredRos/manual-pr225. Have you looked into creating the plots with the
right grid size automatically?

**Comment by oschulz** [comment]
Is this ready to merge, or WIP?

**Comment by fredRos** [comment]
My comments from above still have to be addressed. We really have to fix the plots in BAT first, then we can include them automatically in the manual

**Comment by fredRos** [comment]
I fixed my requests myself, resolved conflicts, and rebased `manual` to the current `master`

**Pull request closed without merging**
