### PR TITLE
Fixed root dictionary generation on OS-X and for out-of-tree builds

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by greenwald** [comment]
@oschulz, @fredRos and I discussed some possible changes to the ROOT dict building that I meant to post to a new issue yesterday. But I forgot:

Are we creating too many ROOT distionaries? We create them for abstract classes that can never be instantiated in ROOT anyway. As far as I see, we only need BCH1D and BCH2D. But it would then also be nice to have our `bat-project.sh`-created Makefile also create a ROOT dict for user-written models.

Thoughts?

**Comment by oschulz** [comment]
> I discussed some possible changes to the ROOT dict building

Whatever you're planning, please keep in mind that is wasn't easy to get this to work with both ROOT-5 and 6. Any change will need extensive testing on all platforms with in-tree build, out-of-tree build, multiple ROOT versions, etc. ...

> Are we creating too many ROOT distionaries? We create them for abstract classes

I don't think we create too many. Dictionaries for abstract classes are useful (and in case of ROOT-5 maybe even necessary). Even if the class is not instantiated, you may want to use a pointer to the abstract class in a ROOT script - so ROOT still needs to know the interface of the class.

> But it would then also be nice to have our bat-project.sh-created Makefile also create a ROOT dict for user-written models

Nice but not entirely trivial to realize. On the other hand, as long as the user sets `$CPATH` correctly, and uses "#include", at least ROOT-6 should find his classes. IMHO `bat-project.sh` is only useful for toy-projects anyhow. Serious long-term projects should use a real build system (e.g. derived from [template-hep-project](https://github.com/oschulz/template-hep-project) or similar sources).

**Comment by greenwald** [comment]
Sorry, I wasn't entirely clear: Our plan was to ask you to look into it.

**Comment by oschulz** [comment]
Let's discuss that by email. :-)

**Pull request merged**
