### PR TITLE
documentation and building

### PR DESCRIPTION
**Pull request by fredRos**

### CODE REVIEW

**Comment by oschulz** [comment]
Fails on `make distcheck`:

    make[1]: *** No rule to make target `readme.devel', needed by `distdir'.  Stop.

**Comment by fredRos** [comment]
Sorry, we so need a build server. `make distcheck` works on my machine

**Comment by oschulz** [comment]
> Sorry, we so need a build server. make distcheck works on my machine

I do have plans in motion, but it'll take a while longer. :-(

**Comment by oschulz** [comment]
> make distcheck works on my machine

It failed for me on both Ubuntu-14.04 and OS-X, with both ROOT-5 and ROOT-6.

**Comment by fredRos** [comment]
What was the error? I noticed already some time ago that `make distcheck` fails if I don't to `make clean` first. I guess that's a bug but it has nothing to do with the commits in this pull request. How exactly did you invoke `make distcheck` and what came out?

**Comment by oschulz** [comment]
> What was the error?

Sorry, I accidentially removed that log file. Anyhow, I ran it again just now and everything is fine. Oh, well - I put it down under random computer weirdness.

> I noticed already some time ago that make distcheck fails if I don't to make clean first.

I always run each tests on a fresh Git clone of BAT.

**Pull request merged**
