### PR TITLE
Fixed storing of fMCMCTree, at random beeing unreadable while writing [FAILS TESTS]

### PR DESCRIPTION
**Pull request by sdorheim**
TTree->SetAutoSave somehow conflicts with AutoSave("SaveSelf") and the tree becomes unreadable when writing

This fixed this issue

### CODE REVIEW

**Comment by fredRos** [comment]
@sdorheim says: only tested with root 5, so check with root 6, too. Should make file readable anytime during prerun and mainrun. Right now it's randomly readable during the mainrun and not readable during prerun

**Comment by fredRos** [comment]
I tested with root 6.06 and it worked fine. I didn't know how to easily put this into a unit test, so I post my setup here in case we need to do it again.

#### Slow down the likelihood
Modify `examples/basic/rootOutput/GaussModel.cxx`

```c++
double GaussModel::LogLikelihood(const std::vector<double>& parameters)
{
    for (unsigned long i = 0 ; i < 4e6 ; ++i)
        BCMath::LogFact(10);
...
```

#### Try to read parameters
Create a macro `examples/basic/rootOutput/readFile.C`:
```c++
#include <TFile.h>
#include <TTree.h>

void readFile()
{
    TFile* f = TFile::Open("GaussModel.root", "READ");
    TTree* tmcmc = NULL;
    f->GetObject("gausMod_mcmc", tmcmc);
    tmcmc->Scan();
}
```

#### Run the Markov chain

In `examples/basic/rootOutput/`, do `make && ./runRootOutput`. In a separate shell, run `readFile.C` after the first efficiency check, when the first parameter values should be stored to the file
```
## shell 1 ##

$ make && ./runRootOutput
...
Summary : Marginalize using Metropolis
Summary : Pre-run Metropolis MCMC for model "gausMod" ...
Summary :  --> Perform MCMC pre-run with 4 chains, each with maximum 100000 iterations
Detail  :      * Efficiency status: Efficiencies not within predefined range after 500 iterations. Efficiency of 
Detail  :          chain 1 is below 15 % (7 %). Scale decreased to 1.259
Detail  :          chain 2 is below 15 % (12 %). Scale decreased to 1.259
Detail  :          chain 3 is below 15 % (9 %). Scale decreased to 1.259
```

With the bug, I get

```
## shell 2 ##

$ root -q readFile.C 
root [0] 
Processing readFile.C...
************************************************************************************************************
*    Row   * Chain.Cha * Iteration * Phase.Pha * LogProbab *         x *         y *         z * LogLikeli *
************************************************************************************************************
************************************************************************************************************
```
After applying @sdorheim 's patch, I see
```
## shell 2 ##

$ root -b -q readFile.C 
root [0] 
Processing readFile.C...
************************************************************************************************************
*    Row   * Chain.Cha * Iteration * Phase.Pha * LogProbab *         x *         y *         z * LogLikeli *
************************************************************************************************************
*        0 *         0 *         1 *        -1 *           * 0.0511284 * -4.638926 * -2.960616 *           *
*        1 *         1 *         1 *        -1 *           * 47.433558 * -3.358229 * 4.8071141 *           *
*        2 *         2 *         1 *        -1 *           * -8.232162 * -0.021546 * -0.925613 *           *
*        3 *         3 *         1 *        -1 *           * 21.290659 * 1.3118073 * -0.545285 *           *
*        4 *         0 *         2 *        -1 *           * 0.0511284 * -4.638926 * -2.960616 *           *
*        5 *         1 *         2 *        -1 *           * 47.433558 * -3.358229 * 4.8071141 *           *
...
```

@oschulz please check merge with master if tests pass on all platforms. We then should cherry-pick on the 1.0 release branch, too.

**Comment by oschulz** [comment]
Unfortunately, some tests fail.

Ubuntu 14.04, ROOT-6:

```
[...]
PASS: BCPrior.TEST
FAIL: BCEngineMCMC.TEST
FAIL: BCSummaryTool.TEST
FAIL: BCIntegrate.TEST
PASS: parallel.TEST
[...]
```

Ubuntu 14.04, ROOT-5:

```
[...]
PASS: BCPrior.TEST
../../test-driver: line 107: 18506 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: BCEngineMCMC.TEST
FAIL: BCSummaryTool.TEST
../../test-driver: line 107: 18860 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: BCIntegrate.TEST
../../test-driver: line 107: 19092 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
PASS: parallel.TEST
[...]
```

Same tests fail on OS-X, too. Current master of BAT passes all tests.

**Comment by sdorheim** [comment]
I'll investigate the fails over the weekend.

**Comment by fredRos** [comment]
From the ROOT documentation, the `AutoSave` method promises to do what we want
https://root.cern.ch/doc/master/classTTree.html#a76259576b0094536ad084cde665c13a8

but it produces random crashes in the unit tests. For fun, I  changed the frequency of saving with 
    if (nChecks > 0 && nChecks % 5 == 0){
in `BCEngineMCMC`. Then `parallel.TEST` doesn't crash. I really wonder if the cause is a heap corruption that be caused somewhere else. I tried valgrind but it didn't tell me anything useful.

**Comment by talismanbrandi** [comment]
Hi,

This topic is a bit old but I finally got to testing this with [HEPfit](https://github.com/talismanbrandi/HEPfit) TTree->SetAutoSave() works fine for me with AutoSave("SaveSelf") in root 5. We also use it in [HEPfit](https://github.com/talismanbrandi/HEPfit) to write our observable tree. I have checked that the tree produced is readable.

**Comment by oschulz** [comment]
Still fails tests.

**Pull request closed without merging**
